apiVersion: schemas.schemahero.io/v1alpha2
kind: Table
metadata:
  name: users
spec:
  database: testdb
  name: users
  requires: []
  schema:
    postgres:
      primaryKey: [id]
      columns:
        - name: id
          type: integer
        - name: login
          type: varchar(255)
        - name: name
          type: varchar(255)
