name: SchemaHero Plan

on:
  pull_request:
    branches:
      - master

jobs:
  retrieve_plan:
    name: Retrieve Plan
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://schemahero/schemahero-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  comment:
    name: Comment
    runs-on: ubuntu-18.04
    needs: retrieve_plan
    steps:
      - uses: actions/checkout@v1
