name: SchemaHero Plan

on:
  pull_request:
    branches:
      - master

jobs:
  retrieve_plan:
    name: Retrieve Plan
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/schemahero-plan
  comment:
    name: Comment
    runs-on: ubuntu-18.04
    needs: retreive_plan
    steps:
      - uses: actions/checkout@v1
